object ListFormBaseFrm: TListFormBaseFrm
  Left = 192
  Top = 160
  Align = alClient
  BorderStyle = bsNone
  Caption = 'ListFormBaseFrm'
  ClientHeight = 442
  ClientWidth = 912
  Color = 16511980
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 12
end
