program Neo;

uses
  ShareMem,
  Forms,
  SysUtils,
  FrmCliMain in 'FrmCliMain.pas' {FMCliMain},
  untFunctions in '..\Comm\GobUnit\untfunctions.pas',
  ZLibEx in '..\Comm\GobUnit\ZLIBEX.pas',
  UntTIO in '..\Comm\GobUnit\UntTIO.pas',
  FrmCliDM in '..\ERP\FrmCliDM.pas' {CliDM: TDataModule},
  DCPbase64 in '..\Comm\DCPbase64.pas',
  FrmLogin in 'FrmLogin.pas' {FMLotin},
  Pub_Fun in '..\Comm\Pub_Fun.pas',
  CommonConstPublic in '..\ERP\STReport\CommonConstPublic.pas',
  uBaseEditFrm in '..\ERP\Base\uBaseEditFrm.pas' {STBaseEdit},
  Frm_TranUpDate in '..\ERP\Frm_TranUpDate.pas' {FM_TranUpDate},
  dSLPFrm in '..\ERP\POSEdit\dSLPFrm.pas' {dSLPForm},
  Frm_ChangePwd in '..\ERP\Frm_ChangePwd.pas' {FM_ChangePwd},
  uHangFrm in '..\ERP\POSEdit\uHangFrm.pas' {FrmHang},
  uSalesManFrm in '..\ERP\POSEdit\uSalesManFrm.pas' {FrmSalesMan},
  Frm_BillListBase in '..\ERP\Base\Frm_BillListBase.pas' {FM_BillListBase},
  Frm_BillSerch in '..\ERP\Base\Frm_BillSerch.pas' {FM_BillSerch},
  Frm_BillEditBase in '..\ERP\Base\Frm_BillEditBase.pas' {FM_BillEditBase},
  ureliefFrm in '..\ERP\POSEdit\ureliefFrm.pas' {FrmRelief},
  uShowStoragefrm in '..\ERP\POSEdit\uShowStoragefrm.pas' {dShowStorageform},
  uLockSysFrm in '..\ERP\POSEdit\uLockSysFrm.pas' {FrmLockSys},
  uDayBalanceFrm in '..\ERP\POSEdit\uDayBalanceFrm.pas' {FrmDayBalance},
  RMReport_lib in '..\ERP\STReport\RMReport_lib.pas',
  FrmSelectReport in '..\ERP\STReport\FrmSelectReport.pas' {FMSelectReport},
  uEarnestMoneyFrm in '..\ERP\POSEdit\uEarnestMoneyFrm.pas' {FrmHangOut},
  uExplain_StyleFrm in '..\ERP\POSEdit\uExplain_StyleFrm.pas' {FM_Explain_Style},
  uExplain_BillFrm in '..\ERP\POSEdit\uExplain_BillFrm.pas' {FM_Explain_Bill},
  uFrmFillFreightFrm in '..\ERP\OtherBill\uFrmFillFreightFrm.pas' {FrmFillFreight},
  uBillList_FillFreight_Frm in '..\ERP\OtherBill\uBillList_FillFreight_Frm.pas' {FrmBillList_FillFreight},
  uSysDataSelect in '..\ERP\Base\uSysDataSelect.pas' {SysDataSelectFrm},
  uBillList_POS_Frm in '..\ERP\POSEdit\uBillList_POS_Frm.pas' {Frm_BillListPOS},
  uBillList_T_FA_FaDispatchBillFrm in '..\ERP\OtherBill\uBillList_T_FA_FaDispatchBillFrm.pas' {FM_BillList_T_FA_FaDispatchBill},
  uBillList_T_IM_MoveIssueBillFrm in '..\ERP\OtherBill\uBillList_T_IM_MoveIssueBillFrm.pas' {FM_BillListT_IM_MoveIssueBill},
  uBillList_T_IM_MoveInWarehsBillFrm in '..\ERP\OtherBill\uBillList_T_IM_MoveInWarehsBillFrm.pas' {FM_BillListT_IM_MoveInWarehsBill},
  uFrm_MoveIssueBill in '..\ERP\OtherBill\uFrm_MoveIssueBill.pas' {FM_BillEditMoveIssue},
  uFrm_PurInWarehsBill in '..\ERP\OtherBill\uFrm_PurInWarehsBill.pas' {FM_BillEditMoveinwarehs},
  Frm_SysComfig in '..\ERP\Frm_SysComfig.pas' {FM_SysComfig},
  uVIPCardInput in '..\ERP\POSEdit\uVIPCardInput.pas' {FrmVIPCardInput},
  uEmitAssociatorCard in '..\ERP\POSEdit\uEmitAssociatorCard.pas' {EmitAssociatorCard},
  uPOSAlterDate_Frm in '..\ERP\POSEdit\uPOSAlterDate_Frm.pas' {FrmPOSAlterDate},
  uAssociatorCardList_Frm in '..\ERP\POSEdit\uAssociatorCardList_Frm.pas' {Frm_AssociatorCardList},
  uMaterialListFrm in '..\ERP\POSEdit\uMaterialListFrm.pas' {Frm_MaterialList},
  uBillList_CT_BIL_RETAILPOSFrm in '..\ERP\OtherBill\uBillList_CT_BIL_RETAILPOSFrm.pas' {FM_BillListCheck},
  QueryThread in '..\ERP\QueryThread.pas',
  uTuiHuoFrm in '..\ERP\POSEdit\uTuiHuoFrm.pas' {FrmTuiHuo},
  materialinfo in '..\ERP\materialinfo.pas' {FrmMaterialinfo},
  frmImpDataFromPos in '..\ERP\frmImpDataFromPos.pas' {ImpDataFromPosForm},
  Maximage in '..\ERP\Maximage.pas' {FrmMaxImage},
  CheckQty in '..\ERP\CheckQty.pas' {FrmCheckQty},
  uReportBaseFrm in '..\ERP\Base\uReportBaseFrm.pas' {ReportBaseFrm},
  SaleDayReport in '..\ERP\SaleDayReport.pas' {SaleDayReportFrm},
  Frm_TolZB in '..\ERP\Frm_TolZB.pas' {FM_TolZB},
  uSaleListAy in '..\ERP\uSaleListAy.pas' {SaleListAyFrm},
  uPromtCount in '..\ERP\uPromtCount.pas' {PromtCountFrm},
  uNmarketable in '..\ERP\uNmarketable.pas' {UnmarketableFrm},
  uSaleGZAY in '..\ERP\uSaleGZAY.pas' {SaleGZAYFrm},
  uGridStyleSet in '..\ERP\uGridStyleSet.pas' {GridStyleSetFrm},
  uLogQuery in '..\ERP\uLogQuery.pas' {LogQuery},
  uFormTxtImport in '..\ERP\uFormTxtImport.pas' {FormTxtImportFrm},
  uQueryPosStock in '..\ERP\uQueryPosStock.pas' {QueryPosStockFrm},
  uSubsidiary_trace_report in '..\ERP\uSubsidiary_trace_report.pas' {subsidiary_trace_reportFrm},
  uTransf_trace_report in '..\ERP\uTransf_trace_report.pas' {transf_trace_reportFrm},
  uVipAyReportFrm in '..\ERP\uVipAyReportFrm.pas' {VipAyReportFrm},
  uDayBalance in '..\ERP\uDayBalance.pas' {DayBalanceFrm},
  uBusinessDataCollection in '..\ERP\uBusinessDataCollection.pas' {BusinessDataCollectionFrm},
  uBusinessDataC in '..\ERP\uBusinessDataC.pas' {BusinessDcFrm},
  uFrm_CheckBillState in '..\ERP\OtherBill\uFrm_CheckBillState.pas' {CheckBillStateFrm},
  uBalanceHandFrm in '..\ERP\POSEdit\uBalanceHandFrm.pas' {Frm_BalanceHand},
  Frm_Ping in '..\ERP\Frm_Ping.pas' {FM_Ping},
  Frm_ChangeLine in '..\ERP\Frm_ChangeLine.pas' {FM_ChangeLine},
  uFrm_BillEditCheckDiff in '..\ERP\OtherBill\uFrm_BillEditCheckDiff.pas' {FM_BillEditCheck_Diff},
  uFrm_AcrossInput in '..\ERP\OtherBill\uFrm_AcrossInput.pas' {Frm_AcrossInput},
  uFrm_DiffDB in '..\ERP\Report\uFrm_DiffDB.pas' {Frm_DiffDB},
  uReportFrm_MasterList in '..\ERP\Report\uReportFrm_MasterList.pas' {ReportFrm_MasterList},
  uProrateFrm in '..\ERP\POSEdit\uProrateFrm.pas' {Frm_Prorate},
  uFrm_CheckAffirm in '..\ERP\OtherBill\uFrm_CheckAffirm.pas' {Frm_CheckAffirm},
  uCheckSaveStorageFrm in '..\ERP\OtherBill\uCheckSaveStorageFrm.pas' {Frm_CheckSaveStorage},
  uCheckReportFrm in '..\ERP\OtherBill\uCheckReportFrm.pas' {Frm_CheckReport},
  uFrm_CheckBill in '..\ERP\OtherBill\uFrm_CheckBill.pas' {Frm_CheckBill},
  SalesManSatiscReport in '..\ERP\SalesManSatiscReport.pas' {SaleManSatiscReportForm},
  uFrm_ImportXLS_CHECK in '..\ERP\OtherBill\uFrm_ImportXLS_CHECK.pas' {FrmImportXlSCheck},
  uFrm_TxtFromat in '..\ERP\OtherBill\uFrm_TxtFromat.pas' {FrmTxtFromatSet},
  uFrm_ImportXLS_Base in '..\ERP\OtherBill\uFrm_ImportXLS_Base.pas' {FrmImportXlSBase},
  uDayReceiveTypeFrm in '..\ERP\POSEdit\uDayReceiveTypeFrm.pas' {FrmDayReceiveType},
  uFrm_InOutStoReport in '..\ERP\Report\uFrm_InOutStoReport.pas' {InOutStoQtyReportFrm},
  uFrm_AcrossInput_Base in '..\ERP\Base\uFrm_AcrossInput_Base.pas' {Frm_AcrossInput_Base},
  uSelectBaseInfoFrm in '..\ERP\POSEdit\uSelectBaseInfoFrm.pas' {Frm_SelectBaseInfo},
  uCodeShaoMiaoFrm in '..\ERP\Base\uCodeShaoMiaoFrm.pas' {FrmCodeShaoMiao},
  uBillList_PurOrder in '..\ERP\OtherBill\uBillList_PurOrder.pas' {FM_BillListPurOrder},
  uBillEditPurOrder in '..\ERP\OtherBill\uBillEditPurOrder.pas' {FM_BillEditPurOrder},
  uBillListPurInWarehs in '..\ERP\OtherBill\uBillListPurInWarehs.pas' {FM_BillListPurInWarehs},
  uBillListPurInWarehsReturn in '..\ERP\OtherBill\uBillListPurInWarehsReturn.pas' {FM_BillListPurInWarehsReturn},
  uBillEditPurInWarehs in '..\ERP\OtherBill\uBillEditPurInWarehs.pas' {FM_BillEditPurInWarehs},
  uBillEditPurInWarehsReturn in '..\ERP\OtherBill\uBillEditPurInWarehsReturn.pas' {FM_BillEditPurInWarehsReturn},
  uBillListPurReturns in '..\ERP\OtherBill\uBillListPurReturns.pas' {FM_BillListPurReturns},
  uDutyCheckIn in '..\ERP\POSEdit\uDutyCheckIn.pas' {frmDutyCheckIn},
  uCashStoragefrm in '..\ERP\POSEdit\uCashStoragefrm.pas' {frmCashStorage},
  uCacthCashierfrm in '..\ERP\POSEdit\uCacthCashierfrm.pas' {frmCacthCash},
  uCashBookfrm in '..\ERP\POSEdit\uCashBookfrm.pas' {frmCashBook},
  uLeaveCheckInfrm in '..\ERP\POSEdit\uLeaveCheckInfrm.pas' {frmLeaveCheckIn},
  uFrm_Order_trace_report in '..\ERP\Report\uFrm_Order_trace_report.pas' {Order_trace_reportFrm},
  uFrmEnvirTesting in '..\ERP\uFrmEnvirTesting.pas' {Frm_Environmentaltesting},
  uQueryJointlyRageFrm in '..\ERP\Report\uQueryJointlyRageFrm.pas' {QueryJointlyRageFrm},
  uVipBase in '..\ERP\OtherBill\uVipBase.pas' {VipBaseFrm},
  uVipBaseList_Frm in '..\ERP\POSEdit\uVipBaseList_Frm.pas' {VipBaseListListFrm},
  uNoCardVipFind_Frm in '..\ERP\POSEdit\uNoCardVipFind_Frm.pas' {NoVipListFrm},
  uExportExcelFrm in '..\ERP\uExportExcelFrm.pas' {ExportExcelFrm},
  uSendMessage in '..\ERP\Report\uSendMessage.pas' {SendMessageFrm},
  uReportFindvalue in '..\ERP\Report\uReportFindvalue.pas' {ReportFindvalueFrm},
  md5 in '..\Comm\md5.pas',
  uFrm_InOutStoByDateReport in '..\ERP\Report\uFrm_InOutStoByDateReport.pas' {InOutStoQtyByDateReportFrm},
  uFrm_IOSUMByDateReport in '..\ERP\Report\uFrm_IOSUMByDateReport.pas' {IOSUMByDateReportFrm},
  frm_UpdatePOSBizDate in '..\ERP\frm_UpdatePOSBizDate.pas' {FM_UpdatePOSBizDateForm},
  uTSView in '..\ERP\uTSView.pas' {TSViewFrm},
  uVipSQ in '..\ERP\OtherBill\uVipSQ.pas' {VipSQFrm},
  uPOSFormTxtImport in '..\ERP\POSEdit\uPOSFormTxtImport.pas' {POSFormTxtImportFrm},
  ReturnAMTListfrm in '..\ERP\OtherBill\ReturnAMTListfrm.pas' {ReturnAMTListForm},
  uJXCList in '..\ERP\Report\uJXCList.pas' {JXCListFrm},
  uBillViewViewFrm in '..\ERP\Report\uBillViewViewFrm.pas' {BillViewViewFrm},
  ShopSalesPerformance in '..\ERP\ShopSalesPerformance.pas' {ShopSalesPerformanceForm},
  uVipCurrentValue in '..\ERP\OtherBill\uVipCurrentValue.pas' {VipCurrentValue},
  uShopSalesPerformanceEditBill in '..\ERP\uShopSalesPerformanceEditBill.pas' {ShopSalesPrformanceForm},
  uBillList_SalePerBillFrm in '..\ERP\uBillList_SalePerBillFrm.pas' {FM_BillList_SalePerForm},
  uVipListDataFindFrm in '..\ERP\Report\uVipListDataFindFrm.pas' {VipListDataFindFrm},
  uBillList_T_IM_Otherissuebill in '..\ERP\OtherBill\uBillList_T_IM_Otherissuebill.pas' {FM_BillListT_IM_Otherissuebill},
  uStockZTAyFrm in '..\ERP\Report\uStockZTAyFrm.pas' {StockZTAyFrm},
  uManyVipShopping in '..\ERP\OtherBill\uManyVipShopping.pas' {ManyVipShopping},
  uFrm_SaleByDayAlz in '..\ERP\Report\uFrm_SaleByDayAlz.pas' {FormSaleByDayAlz},
  uVipPassWordUpdate in '..\ERP\uVipPassWordUpdate.pas' {VIPPswdupdate},
  uInputVipPswdFrm in '..\ERP\uInputVipPswdFrm.pas' {InputVipPswdFrm},
  uPlayTypeView in '..\ERP\OtherBill\uPlayTypeView.pas' {playTypeViewFrm},
  uSelectMaterialInfo in '..\ERP\OtherBill\uSelectMaterialInfo.pas' {SelectMaterialInfoFrm},
  uAlterLevel in '..\ERP\BaseData\uAlterLevel.pas' {AlterLevelFrm},
  uTreeBaseEditFrm in '..\ERP\Base\uTreeBaseEditFrm.pas' {TreeBaseEditFrm},
  uSystemMenuEditFrm in '..\ERP\BaseData\uSystemMenuEditFrm.pas' {SystemMenuEditFrm},
  uAssDataItemEditFrm in '..\ERP\BaseData\uAssDataItemEditFrm.pas' {AssDataItemEditFrm},
  uAssDataTypeEditFrm in '..\ERP\BaseData\uAssDataTypeEditFrm.pas' {AssDataTypeEditFrm},
  uListFormBaseFrm in '..\ERP\BaseData\uListFormBaseFrm.pas' {ListFormBaseFrm},
  uSelecDataBaseFrm in '..\ERP\BaseData\uSelecDataBaseFrm.pas' {SelecDataBaseFrm},
  uSelectClientFrm in '..\ERP\BaseData\uSelectClientFrm.pas' {SelectClientFrm},
  uselectSuppliersFrm in '..\ERP\BaseData\uselectSuppliersFrm.pas' {selectSuppliersFrm},
  uSelectWarehouseFrm in '..\ERP\BaseData\uSelectWarehouseFrm.pas' {SelectWarehouseFrm},
  uGroupStandard in '..\ERP\BaseData\uGroupStandard.pas' {GroupStandardFrm},
  uBranchEditFrm in '..\ERP\BaseData\uBranchEditFrm.pas' {BranchEditFrm},
  uUserInfofrm in '..\ERP\BaseData\uUserInfofrm.pas' {FM_UserInfoForm},
  uUserEditfrm in '..\ERP\BaseData\uUserEditfrm.pas' {FM_UserEditForm},
  uMaterTypeTreeEditFrm in '..\ERP\BaseData\uMaterTypeTreeEditFrm.pas' {MaterTypeTreeEditFrm},
  uClienSupperTreeEditFrm in '..\ERP\BaseData\uClienSupperTreeEditFrm.pas' {ClienSupperTreeEditFrm},
  uSelectMaterialFrm in '..\ERP\BaseData\uSelectMaterialFrm.pas' {SelectMaterialFrm},
  uUserRolefrm in '..\ERP\BaseData\uUserRolefrm.pas' {FM_UserRoleForm},
  StringUtilClass in '..\Comm\StringUtilClass.pas',
  uMsgListDlg in '..\ERP\Base\uMsgListDlg.pas' {MsgListDlg},
  uMaterialEditFrm in '..\ERP\BaseData\uMaterialEditFrm.pas' {uDrpHelperClass},
  uUserBranchScopefrm in '..\ERP\BaseData\uUserBranchScopefrm.pas' {FM_UserBranchScopeForm},
  uOrgFrm in '..\ERP\BaseData\uOrgFrm.pas' {OrgFrm},
  uMaterDataSelectHelper in '..\ERP\HelperClass\uMaterDataSelectHelper.pas',
  uSelectData in '..\ERP\BaseData\uSelectData.pas',
  uRoleListfrm in '..\ERP\BaseData\uRoleListfrm.pas' {FM_RoleListForm},
  uRoleEditFrm in '..\ERP\BaseData\uRoleEditFrm.pas' {FM_RoleEditForm},
  uAllocUserfrm in '..\ERP\BaseData\uAllocUserfrm.pas' {FM_AllocUserRole},
  uCustomerEditfrm in '..\ERP\BaseData\uCustomerEditfrm.pas' {FM_CUstomerEditForm},
  uDrpHelperClase in '..\ERP\HelperClass\uDrpHelperClase.pas',
  uWarehouseEditFrm in '..\ERP\BaseData\uWarehouseEditFrm.pas' {WarehouseEditFrm},
  uSupplierEditFrm in '..\ERP\BaseData\uSupplierEditFrm.pas' {STBaseEdit1},
  uWarehouseSetFrm in '..\ERP\BaseData\uWarehouseSetFrm.pas' {WarehouseSetFrm},
  uDepartmentFrm in '..\ERP\BaseData\uDepartmentFrm.pas' {DepartmentFrm},
  uPersonListFrm in '..\ERP\BaseData\uPersonListFrm.pas' {PersonListFrm},
  uuPersonEditFrm in '..\ERP\BaseData\uuPersonEditFrm.pas' {uPersonEditFrm},
  uParaNavMenuItemfrm in '..\ERP\BaseData\uParaNavMenuItemfrm.pas' {FM_ParaNavMenuItemForm},
  uParameterSetfrm in '..\ERP\BaseData\uParameterSetfrm.pas' {FM_ParamSetForm},
  uSelectParamScopefrm in '..\ERP\BaseData\uSelectParamScopefrm.pas' {FM_SelectParamScopeForm},
  uBaseDataListFrm in '..\ERP\BaseData\uBaseDataListFrm.pas' {BaseDataListFrm},
  uBasedataEditFrm in '..\ERP\BaseData\uBasedataEditFrm.pas' {BasedataEditFrm},
  uCodeTableFrm in '..\ERP\BaseData\uCodeTableFrm.pas' {CodeTableFrm},
  uCodeTableEditFrm in '..\ERP\BaseData\uCodeTableEditFrm.pas' {CodeTableEditFrm},
  uParamEditfrm in '..\ERP\BaseData\uParamEditfrm.pas' {FM_ParamEditForm},
  uSizeGroupListFrm in '..\ERP\BaseData\uSizeGroupListFrm.pas' {SizeGroupListFrm},
  uSizeGroupEditFrm in '..\ERP\BaseData\uSizeGroupEditFrm.pas' {SizeGroupEditFrm},
  uReadCodeScenarioListFrm in '..\ERP\BaseData\uReadCodeScenarioListFrm.pas' {ReadCodeScenarioListFrm},
  uReadCodeScenarioEditFrm in '..\ERP\BaseData\uReadCodeScenarioEditFrm.pas' {ReadCodeScenarioEditFrm},
  uPermissionsEditFrm in '..\ERP\BaseData\uPermissionsEditFrm.pas' {PermissionsEditFrm},
  PermissionAgtFrm in '..\ERP\BaseData\PermissionAgtFrm.pas' {PermissionAssignmentFrm},
  uBillQueryFrm in '..\ERP\BaseData\uBillQueryFrm.pas' {BillQueryFrm},
  uBillQuerySQLEditFrm in '..\ERP\BaseData\uBillQuerySQLEditFrm.pas' {BillQuerySQLEditFrm},
  uBillListQueryDialogFrm in '..\ERP\BaseData\uBillListQueryDialogFrm.pas' {BillListQueryDialogFrm},
  uBillQuerySelectFrm in '..\ERP\BaseData\uBillQuerySelectFrm.pas' {BillQuerySelectFrm},
  uBillQuerySelectDateFrm in '..\ERP\BaseData\uBillQuerySelectDateFrm.pas' {BillQuerySelectDateFrm},
  uSmsSystemSetFrm in '..\ERP\BaseData\uSmsSystemSetFrm.pas' {SmsSystemSetFrm},
  uSmsSendQueryFrm in '..\ERP\BaseData\uSmsSendQueryFrm.pas' {SmsSendQueryFrm},
  uPrintQueryFrm in '..\ERP\BaseData\uPrintQueryFrm.pas' {PrintQueryFrm},
  uPrintTemplateDesign in '..\ERP\BaseData\uPrintTemplateDesign.pas' {PrintTemplateDesign},
  uINTERCODEPREFIXEdit in '..\ERP\BaseData\uINTERCODEPREFIXEdit.pas' {INTERCODEPREFIXEditFrm},
  uINTERCODEPREFIXListFrm in '..\ERP\BaseData\uINTERCODEPREFIXListFrm.pas' {INTERCODEPREFIXListFrm},
  uCreateInterCode in '..\ERP\BaseData\uCreateInterCode.pas' {CreateInterCode},
  uBarCodePrintFrm in '..\ERP\BaseData\uBarCodePrintFrm.pas' {BarCodePrintFrm},
  uI3BaseFrm in '..\ERP\Base\uI3BaseFrm.pas' {I3BaseFrm},
  uPrintTemplateSelectFrm in '..\ERP\BaseData\uPrintTemplateSelectFrm.pas' {PrintTemplateSelectFrm},
  uAlterPriceEditFrm in '..\ERP\BaseData\uAlterPriceEditFrm.pas' {AlterPriceEditFrm},
  uAlterPriceListFrm in '..\ERP\BaseData\uAlterPriceListFrm.pas' {AlterPriceListFrm},
  uPriceAlterGuide in '..\ERP\BaseData\uPriceAlterGuide.pas' {PriceAlterGuide},
  uAlterPriceQuery in '..\ERP\BaseData\uAlterPriceQuery.pas' {AlterPriceQuery},
  uBillEditPurRequset in '..\ERP\OtherBill\uBillEditPurRequset.pas' {FM_BillEditPurRequest},
  uBillEditPurReceive in '..\ERP\OtherBill\uBillEditPurReceive.pas' {FM_BillEditPurReceive},
  uBillEditPurInStock in '..\ERP\OtherBill\uBillEditPurInStock.pas' {FM_BillEditPurInStock},
  uBillEditSaleOrder in '..\ERP\SaleBIll\uBillEditSaleOrder.pas' {FM_BillEditSaleOrder},
  uBillList_SaleOrder in '..\ERP\SaleBIll\uBillList_SaleOrder.pas' {FM_BillListSaleOrder},
  uBillEditPostReq in '..\ERP\SaleBIll\uBillEditPostReq.pas' {FM_BillEditPostReq},
  uBillListPurInStock in '..\ERP\OtherBill\uBillListPurInStock.pas' {FM_BillListPurInStock},
  uBillListPurReceive in '..\ERP\OtherBill\uBillListPurReceive.pas' {FM_BillListPurReceive},
  uBillList_PostReq in '..\ERP\SaleBIll\uBillList_PostReq.pas' {FM_BillListPostReq},
  uShopAlterPriceEditFrm in '..\ERP\BaseData\uShopAlterPriceEditFrm.pas' {ShopAlterPriceEditFrm},
  uShopAlterPriceListFrm in '..\ERP\BaseData\uShopAlterPriceListFrm.pas' {ShopAlterPriceListFrm},
  uShopPriceAlterGuide in '..\ERP\BaseData\uShopPriceAlterGuide.pas' {ShopPriceAlterGuide},
  uPriceQueryFrm in '..\ERP\BaseData\uPriceQueryFrm.pas' {PriceQueryFrm},
  uBillEditSaleIssue in '..\ERP\SaleBIll\uBillEditSaleIssue.pas' {FM_BillEditSaleIssue},
  uShopAlterPriceQuery in '..\ERP\BaseData\uShopAlterPriceQuery.pas' {ShopAlterPriceQuery},
  uBillList_SaleIssue in '..\ERP\SaleBIll\uBillList_SaleIssue.pas' {FM_BillListSaleIssue},
  uBillEditBranchPO in '..\ERP\OtherBill\uBillEditBranchPO.pas' {FM_BillEditBranchPO},
  uBillList_BranchPO in '..\ERP\OtherBill\uBillList_BranchPO.pas' {FM_BillListBranchPO},
  uPubThreadQuery in '..\ERP\Base\uPubThreadQuery.pas',
  uFindBillQueryFrm in '..\ERP\BaseData\uFindBillQueryFrm.pas' {FindBillQueryFrm},
  uBillUpDownQueryFrm in '..\ERP\Base\uBillUpDownQueryFrm.pas' {BillUpDownQueryFrm},
  uBillEditPurReturns in '..\ERP\OtherBill\uBillEditPurReturns.pas' {FM_BillEditPurRetuens},
  uRemindConfigFrm in '..\ERP\BaseData\uRemindConfigFrm.pas' {RemindConfigFrm},
  uUserRemindConfigFrm in '..\ERP\BaseData\uUserRemindConfigFrm.pas' {UserRemindConfigFrm},
  uBillListPurRequest in '..\ERP\OtherBill\uBillListPurRequest.pas' {FM_BillListPurRequest},
  uBillEditSaleIssueReturn in '..\ERP\SaleBIll\uBillEditSaleIssueReturn.pas' {FM_BillEditSaleIssueReturn},
  uBillList_SaleIssueReturn in '..\ERP\SaleBIll\uBillList_SaleIssueReturn.pas' {FM_BillListSaleIssueReturn},
  uTransactionFrm in '..\ERP\BaseData\uTransactionFrm.pas' {TransactionFrm},
  uTransactionLogQuery in '..\ERP\BaseData\uTransactionLogQuery.pas' {TransactionLogQuery},
  uBillEditPurReturnWarehs in '..\ERP\OtherBill\uBillEditPurReturnWarehs.pas' {FM_BillEditPurReturnWarehs},
  uBillEditSaleReturnRequest in '..\ERP\SaleBIll\uBillEditSaleReturnRequest.pas' {FM_BillEditSaleReturnRequest},
  uBillListSaleReturnRequest in '..\ERP\SaleBIll\uBillListSaleReturnRequest.pas' {FM_BillListSaleReturnRequest},
  uBillEditChanelTrans in '..\ERP\SaleBIll\uBillEditChanelTrans.pas' {FM_BillEditChanelTrans},
  uBillListChanelTrans in '..\ERP\SaleBIll\uBillListChanelTrans.pas' {FM_BillListChanelTrans},
  uExportToAccess in '..\ERP\Base\uExportToAccess.pas' {ExportMainFrm},
  uPushandpullBillBaseFrm in '..\ERP\Base\uPushandpullBillBaseFrm.pas' {PushandpullBillBaseFrm},
  uBillDistributionFrm in '..\ERP\OtherBill\uBillDistributionFrm.pas' {BillDistributionFrm},
  uMaterialDistributionFrm in '..\ERP\OtherBill\uMaterialDistributionFrm.pas' {MaterialDistributionFrm},
  uStockDistributionFrm in '..\ERP\OtherBill\uStockDistributionFrm.pas' {StockDistributionFrm},
  uSaleOrderToPostReq in '..\ERP\CreateBill\uSaleOrderToPostReq.pas' {SaleOrderToPostReqFrm},
  uBillListPurReturnWarehs in '..\ERP\OtherBill\uBillListPurReturnWarehs.pas' {FM_BillListPurReturWarehs},
  uPackingListFrm in '..\ERP\OtherBill\uPackingListFrm.pas' {PackingListFrm},
  uBillEditOtherissuebill in '..\ERP\OtherBill\uBillEditOtherissuebill.pas' {FM_BillEditOtherIssuebill},
  uBillEditOtherinwarehsbill in '..\ERP\OtherBill\uBillEditOtherinwarehsbill.pas' {FM_BillEditOtherInwarehsbill},
  uBillListOtherIssuebillfrm in '..\ERP\OtherBill\uBillListOtherIssuebillfrm.pas' {FM_BillListOtherIssuebill},
  uBillListOtherInwarehsbillfrm in '..\ERP\OtherBill\uBillListOtherInwarehsbillfrm.pas' {FM_BillListOtherInwarehsbill},
  uPackingQueryFrm in '..\ERP\OtherBill\uPackingQueryFrm.pas' {PackingQueryFrm},
  uPackingListReportFrm in '..\ERP\OtherBill\uPackingListReportFrm.pas' {PackingReportFrm},
  uBatchCancelPackingFrm in '..\ERP\OtherBill\uBatchCancelPackingFrm.pas' {BatchCancelPackingFrm},
  uI3AboutFrm in '..\ERP\OtherBill\uI3AboutFrm.pas' {I3AboutFrm},
  uCreditFileFrm in '..\ERP\BaseData\uCreditFileFrm.pas' {CreditFileFrm},
  uOtherBillBaseEditFrm in '..\ERP\Base\uOtherBillBaseEditFrm.pas' {OtherBillBaseEditFrm},
  uBillEditInvInitfrm in '..\ERP\OtherBill\uBillEditInvInitfrm.pas' {FM_BillEditInvInitForm},
  uBillListInvInitFrm in '..\ERP\OtherBill\uBillListInvInitFrm.pas' {FM_BillListInvInitForm},
  uFrm_SCMCheckBill in '..\ERP\OtherBill\uFrm_SCMCheckBill.pas' {Frm_SCMCheckBill},
  uBillListSCMCheck in '..\ERP\OtherBill\uBillListSCMCheck.pas' {FM_BillListSCMCheck},
  uSCMCheckSaveStorageFrm in '..\ERP\OtherBill\uSCMCheckSaveStorageFrm.pas' {Frm_SCMCheckSaveStorage},
  uBillPromotion in '..\ERP\SaleBIll\uBillPromotion.pas' {FM_BillPromotionEdit},
  uTicketRequisition in '..\ERP\POSEdit\uTicketRequisition.pas' {TicketRequisitionFrm},
  uTicketRequisitionList in '..\ERP\POSEdit\uTicketRequisitionList.pas' {TicketRequisitionList},
  uMallCompareListFrm in '..\ERP\POSEdit\uMallCompareListFrm.pas' {MallCompareListFrm},
  uMallCompareEditFrm in '..\ERP\POSEdit\uMallCompareEditFrm.pas' {MallCompareEditFrm},
  uMallCompareFrm in '..\ERP\POSEdit\uMallCompareFrm.pas' {MallCompareFrm},
  uBatchAlterOrderColorFrm in '..\ERP\SaleBIll\uBatchAlterOrderColorFrm.pas' {BatchAlterOrderColorFrm},
  uBatchCloseOrderFrm in '..\ERP\SaleBIll\uBatchCloseOrderFrm.pas' {BatchCloseOrderFrm},
  uOrderAllocateFrm in '..\ERP\SaleBIll\uOrderAllocateFrm.pas' {OrderAllocateFrm},
  uBatchCancelAllocationFrm in '..\ERP\SaleBIll\uBatchCancelAllocationFrm.pas' {BatchCancelAllocationFrm},
  uBillListPromtion in '..\ERP\SaleBIll\uBillListPromtion.pas' {FM_BillListPromt},
  uSaleOrderQueryFrm in '..\ERP\SaleBIll\uSaleOrderQueryFrm.pas' {SaleOrderQueryFrm},
  uServiceAttributeFrm in '..\ERP\BaseData\uServiceAttributeFrm.pas' {ServiceAttributeFrm},
  uServiceAttributeAllocationFrm in '..\ERP\BaseData\uServiceAttributeAllocationFrm.pas' {ServiceAttributeAllocationFrm},
  uPostReqToIsSueFrm in '..\ERP\CreateBill\uPostReqToIsSueFrm.pas' {PostReqToIsSueFrm},
  uPostReqQueryFrm in '..\ERP\SaleBIll\uPostReqQueryFrm.pas' {PostReqQueryFrm},
  uPurOrderSumImpfrm in '..\ERP\OtherBill\uPurOrderSumImpfrm.pas' {PurOrderSumImpForm},
  uRepairEditFrm in '..\ERP\OtherBill\uRepairEditFrm.pas' {RepairEditFrm},
  uRepairListFrm in '..\ERP\OtherBill\uRepairListFrm.pas' {RepairListFrm},
  uSaleFormTxtImport in '..\ERP\SaleBIll\uSALEFormTxtImport.pas' {SaleFormTxtImportFrm},
  uBatchAddOrderMaterialFrm in '..\ERP\SaleBIll\uBatchAddOrderMaterialFrm.pas' {BatchAddOrderMaterialFrm},
  uMoveIssueToMoveInFrm in '..\ERP\CreateBill\uMoveIssueToMoveInFrm.pas' {MoveIssueToMoveInFrm},
  uMoveIssueBillQuery in '..\ERP\OtherBill\uMoveIssueBillQuery.pas' {MoveIssueBillQuery},
  uBillEditStocktransferfrm in '..\ERP\OtherBill\uBillEditStocktransferfrm.pas' {FM_BillEditStockTransFerForm},
  uRepairWOEditFrm in 'rsm\uRepairWOEditFrm.pas' {RepairWOEditFrm},
  uRepairManFrm in 'rsm\uRepairManFrm.pas' {RepairManFrm},
  uPOSEdit in '..\ERP\POSEdit\uPOSEdit.pas' {frmPOSEdit1},
  uPOSEditFrm in '..\ERP\POSEdit\uPOSEditFrm.pas' {FrmPOSEdit},
  uRepairWOListFrm in 'rsm\uRepairWOListFrm.pas' {RepairWOListFrm},
  uCommonUtilsClass in '..\Comm\uCommonUtilsClass.pas';

{$R *.res}
{$I- } //不产生I/O异常类而是把错误代码返回到预定义变量IOResult中
begin
  if pos('-',DateToStr(date)) <=0 then
  begin
    ShowMsg(application.Handle, '系统日期格式必须更改为长日期格式(yyyy-MM-dd),例:1999-09-01',[]);
  end
  else
  begin
    Application.Initialize;
    Application.Title := 'GA集团ERP系统';
  Application.CreateForm(TCliDM, CliDM);
  Application.CreateForm(TFMCliMain, FMCliMain);
  Application.Run;
  end;
end.
