program I3ERP;

uses
  ShareMem,
  Forms,
  SysUtils,
  FrmCliMain in 'FrmCliMain.pas' {FMCliMain},
  untFunctions in '..\Comm\GobUnit\untfunctions.pas',
  ZLibEx in '..\Comm\GobUnit\ZLIBEX.pas',
  UntTIO in '..\Comm\GobUnit\UntTIO.pas',
  FrmCliDM in 'FrmCliDM.pas' {CliDM: TDataModule},
  DCPbase64 in '..\Comm\DCPbase64.pas',
  FrmLogin in 'FrmLogin.pas' {FMLotin},
  Pub_Fun in '..\Comm\Pub_Fun.pas',
  CommonConstPublic in 'STReport\CommonConstPublic.pas',
  uBaseEditFrm in 'Base\uBaseEditFrm.pas' {STBaseEdit},
  uPOSEditFrm in 'POSEdit\uPOSEditFrm.pas' {FrmPOSEdit},
  Frm_TranUpDate in 'Frm_TranUpDate.pas' {FM_TranUpDate},
  dSLPFrm in 'POSEdit\dSLPFrm.pas' {dSLPForm},
  Frm_ChangePwd in 'Frm_ChangePwd.pas' {FM_ChangePwd},
  uHangFrm in 'POSEdit\uHangFrm.pas' {FrmHang},
  uSalesManFrm in 'POSEdit\uSalesManFrm.pas' {FrmSalesMan},
  Frm_BillListBase in 'Base\Frm_BillListBase.pas' {FM_BillListBase},
  Frm_BillSerch in 'Base\Frm_BillSerch.pas' {FM_BillSerch},
  Frm_BillEditBase in 'Base\Frm_BillEditBase.pas' {FM_BillEditBase},
  ureliefFrm in 'POSEdit\ureliefFrm.pas' {FrmRelief},
  uShowStoragefrm in 'POSEdit\uShowStoragefrm.pas' {dShowStorageform},
  uLockSysFrm in 'POSEdit\uLockSysFrm.pas' {FrmLockSys},
  uDayBalanceFrm in 'POSEdit\uDayBalanceFrm.pas' {FrmDayBalance},
  RMReport_lib in 'STReport\RMReport_lib.pas',
  FrmSelectReport in 'STReport\FrmSelectReport.pas' {FMSelectReport},
  uEarnestMoneyFrm in 'POSEdit\uEarnestMoneyFrm.pas' {FrmHangOut},
  uExplain_StyleFrm in 'POSEdit\uExplain_StyleFrm.pas' {FM_Explain_Style},
  uExplain_BillFrm in 'POSEdit\uExplain_BillFrm.pas' {FM_Explain_Bill},
  uFrmFillFreightFrm in 'OtherBill\uFrmFillFreightFrm.pas' {FrmFillFreight},
  uBillList_FillFreight_Frm in 'OtherBill\uBillList_FillFreight_Frm.pas' {FrmBillList_FillFreight},
  uSysDataSelect in 'Base\uSysDataSelect.pas' {SysDataSelectFrm},
  uBillList_POS_Frm in 'POSEdit\uBillList_POS_Frm.pas' {Frm_BillListPOS},
  uBillList_T_FA_FaDispatchBillFrm in 'OtherBill\uBillList_T_FA_FaDispatchBillFrm.pas' {FM_BillList_T_FA_FaDispatchBill},
  uBillList_T_IM_MoveIssueBillFrm in 'OtherBill\uBillList_T_IM_MoveIssueBillFrm.pas' {FM_BillListT_IM_MoveIssueBill},
  uBillList_T_IM_MoveInWarehsBillFrm in 'OtherBill\uBillList_T_IM_MoveInWarehsBillFrm.pas' {FM_BillListT_IM_MoveInWarehsBill},
  uFrm_MoveIssueBill in 'OtherBill\uFrm_MoveIssueBill.pas' {FM_BillEditMoveIssue},
  uFrm_PurInWarehsBill in 'OtherBill\uFrm_PurInWarehsBill.pas' {FM_BillEditMoveinwarehs},
  Frm_SysComfig in 'Frm_SysComfig.pas' {FM_SysComfig},
  uVIPCardInput in 'POSEdit\uVIPCardInput.pas' {FrmVIPCardInput},
  uEmitAssociatorCard in 'POSEdit\uEmitAssociatorCard.pas' {EmitAssociatorCard},
  uPOSAlterDate_Frm in 'POSEdit\uPOSAlterDate_Frm.pas' {FrmPOSAlterDate},
  uAssociatorCardList_Frm in 'POSEdit\uAssociatorCardList_Frm.pas' {Frm_AssociatorCardList},
  uMaterialListFrm in 'POSEdit\uMaterialListFrm.pas' {Frm_MaterialList},
  uBillList_CT_BIL_RETAILPOSFrm in 'OtherBill\uBillList_CT_BIL_RETAILPOSFrm.pas' {FM_BillListCheck},
  QueryThread in 'QueryThread.pas',
  uTuiHuoFrm in 'POSEdit\uTuiHuoFrm.pas' {FrmTuiHuo},
  materialinfo in 'materialinfo.pas' {FrmMaterialinfo},
  frmImpDataFromPos in 'frmImpDataFromPos.pas' {ImpDataFromPosForm},
  Maximage in 'Maximage.pas' {FrmMaxImage},
  CheckQty in 'CheckQty.pas' {FrmCheckQty},
  uReportBaseFrm in 'Base\uReportBaseFrm.pas' {ReportBaseFrm},
  SaleDayReport in 'SaleDayReport.pas' {SaleDayReportFrm},
  Frm_TolZB in 'Frm_TolZB.pas' {FM_TolZB},
  uSaleListAy in 'uSaleListAy.pas' {SaleListAyFrm},
  uPromtCount in 'uPromtCount.pas' {PromtCountFrm},
  uNmarketable in 'uNmarketable.pas' {UnmarketableFrm},
  uSaleGZAY in 'uSaleGZAY.pas' {SaleGZAYFrm},
  uGridStyleSet in 'uGridStyleSet.pas' {GridStyleSetFrm},
  uLogQuery in 'uLogQuery.pas' {LogQuery},
  uFormTxtImport in 'uFormTxtImport.pas' {FormTxtImportFrm},
  uQueryPosStock in 'uQueryPosStock.pas' {QueryPosStockFrm},
  uSubsidiary_trace_report in 'uSubsidiary_trace_report.pas' {subsidiary_trace_reportFrm},
  uTransf_trace_report in 'uTransf_trace_report.pas' {transf_trace_reportFrm},
  uVipAyReportFrm in 'uVipAyReportFrm.pas' {VipAyReportFrm},
  uDayBalance in 'uDayBalance.pas' {DayBalanceFrm},
  uBusinessDataCollection in 'uBusinessDataCollection.pas' {BusinessDataCollectionFrm},
  uBusinessDataC in 'uBusinessDataC.pas' {BusinessDcFrm},
  uFrm_CheckBillState in 'OtherBill\uFrm_CheckBillState.pas' {CheckBillStateFrm},
  uBalanceHandFrm in 'POSEdit\uBalanceHandFrm.pas' {Frm_BalanceHand},
  Frm_Ping in 'Frm_Ping.pas' {FM_Ping},
  Frm_ChangeLine in 'Frm_ChangeLine.pas' {FM_ChangeLine},
  uFrm_BillEditCheckDiff in 'OtherBill\uFrm_BillEditCheckDiff.pas' {FM_BillEditCheck_Diff},
  uFrm_AcrossInput in 'OtherBill\uFrm_AcrossInput.pas' {Frm_AcrossInput},
  uFrm_DiffDB in 'Report\uFrm_DiffDB.pas' {Frm_DiffDB},
  uReportFrm_MasterList in 'Report\uReportFrm_MasterList.pas' {ReportFrm_MasterList},
  uProrateFrm in 'POSEdit\uProrateFrm.pas' {Frm_Prorate},
  uFrm_CheckAffirm in 'OtherBill\uFrm_CheckAffirm.pas' {Frm_CheckAffirm},
  uCheckSaveStorageFrm in 'OtherBill\uCheckSaveStorageFrm.pas' {Frm_CheckSaveStorage},
  uCheckReportFrm in 'OtherBill\uCheckReportFrm.pas' {Frm_CheckReport},
  uFrm_CheckBill in 'OtherBill\uFrm_CheckBill.pas' {Frm_CheckBill},
  SalesManSatiscReport in 'SalesManSatiscReport.pas' {SaleManSatiscReportForm},
  uFrm_ImportXLS_CHECK in 'OtherBill\uFrm_ImportXLS_CHECK.pas' {FrmImportXlSCheck},
  uFrm_TxtFromat in 'OtherBill\uFrm_TxtFromat.pas' {FrmTxtFromatSet},
  uFrm_ImportXLS_Base in 'OtherBill\uFrm_ImportXLS_Base.pas' {FrmImportXlSBase},
  uDayReceiveTypeFrm in 'POSEdit\uDayReceiveTypeFrm.pas' {FrmDayReceiveType},
  uFrm_InOutStoReport in 'Report\uFrm_InOutStoReport.pas' {InOutStoQtyReportFrm},
  uFrm_AcrossInput_Base in 'Base\uFrm_AcrossInput_Base.pas' {Frm_AcrossInput_Base},
  uSelectBaseInfoFrm in 'POSEdit\uSelectBaseInfoFrm.pas' {Frm_SelectBaseInfo},
  uCodeShaoMiaoFrm in 'Base\uCodeShaoMiaoFrm.pas' {FrmCodeShaoMiao},
  uBillList_PurOrder in 'OtherBill\uBillList_PurOrder.pas' {FM_BillListPurOrder},
  uBillEditPurOrder in 'OtherBill\uBillEditPurOrder.pas' {FM_BillEditPurOrder},
  uBillListPurInWarehs in 'OtherBill\uBillListPurInWarehs.pas' {FM_BillListPurInWarehs},
  uBillListPurInWarehsReturn in 'OtherBill\uBillListPurInWarehsReturn.pas' {FM_BillListPurInWarehsReturn},
  uBillEditPurInWarehs in 'OtherBill\uBillEditPurInWarehs.pas' {FM_BillEditPurInWarehs},
  uBillEditPurInWarehsReturn in 'OtherBill\uBillEditPurInWarehsReturn.pas' {FM_BillEditPurInWarehsReturn},
  uBillListPurReturns in 'OtherBill\uBillListPurReturns.pas' {FM_BillListPurReturns},
  uDutyCheckIn in 'POSEdit\uDutyCheckIn.pas' {frmDutyCheckIn},
  uCashStoragefrm in 'POSEdit\uCashStoragefrm.pas' {frmCashStorage},
  uCacthCashierfrm in 'POSEdit\uCacthCashierfrm.pas' {frmCacthCash},
  uCashBookfrm in 'POSEdit\uCashBookfrm.pas' {frmCashBook},
  uLeaveCheckInfrm in 'POSEdit\uLeaveCheckInfrm.pas' {frmLeaveCheckIn},
  uFrm_Order_trace_report in 'Report\uFrm_Order_trace_report.pas' {Order_trace_reportFrm},
  uFrmEnvirTesting in 'uFrmEnvirTesting.pas' {Frm_Environmentaltesting},
  uQueryJointlyRageFrm in 'Report\uQueryJointlyRageFrm.pas' {QueryJointlyRageFrm},
  uVipBase in 'OtherBill\uVipBase.pas' {VipBaseFrm},
  uVipBaseList_Frm in 'POSEdit\uVipBaseList_Frm.pas' {VipBaseListListFrm},
  uNoCardVipFind_Frm in 'POSEdit\uNoCardVipFind_Frm.pas' {NoVipListFrm},
  uExportExcelFrm in 'uExportExcelFrm.pas' {ExportExcelFrm},
  uSendMessage in 'Report\uSendMessage.pas' {SendMessageFrm},
  uReportFindvalue in 'Report\uReportFindvalue.pas' {ReportFindvalueFrm},
  md5 in '..\Comm\md5.pas',
  uFrm_InOutStoByDateReport in 'Report\uFrm_InOutStoByDateReport.pas' {InOutStoQtyByDateReportFrm},
  uFrm_IOSUMByDateReport in 'Report\uFrm_IOSUMByDateReport.pas' {IOSUMByDateReportFrm},
  frm_UpdatePOSBizDate in 'frm_UpdatePOSBizDate.pas' {FM_UpdatePOSBizDateForm},
  uTSView in 'uTSView.pas' {TSViewFrm},
  uVipSQ in 'OtherBill\uVipSQ.pas' {VipSQFrm},
  uPOSFormTxtImport in 'POSEdit\uPOSFormTxtImport.pas' {POSFormTxtImportFrm},
  ReturnAMTListfrm in 'OtherBill\ReturnAMTListfrm.pas' {ReturnAMTListForm},
  uJXCList in 'Report\uJXCList.pas' {JXCListFrm},
  uBillViewViewFrm in 'Report\uBillViewViewFrm.pas' {BillViewViewFrm},
  ShopSalesPerformance in 'ShopSalesPerformance.pas' {ShopSalesPerformanceForm},
  uVipCurrentValue in 'OtherBill\uVipCurrentValue.pas' {VipCurrentValue},
  uShopSalesPerformanceEditBill in 'uShopSalesPerformanceEditBill.pas' {ShopSalesPrformanceForm},
  uBillList_SalePerBillFrm in 'uBillList_SalePerBillFrm.pas' {FM_BillList_SalePerForm},
  uVipListDataFindFrm in 'Report\uVipListDataFindFrm.pas' {VipListDataFindFrm},
  uBillList_T_IM_Otherissuebill in 'OtherBill\uBillList_T_IM_Otherissuebill.pas' {FM_BillListT_IM_Otherissuebill},
  uStockZTAyFrm in 'Report\uStockZTAyFrm.pas' {StockZTAyFrm},
  uManyVipShopping in 'OtherBill\uManyVipShopping.pas' {ManyVipShopping},
  uFrm_SaleByDayAlz in 'Report\uFrm_SaleByDayAlz.pas' {FormSaleByDayAlz},
  uVipPassWordUpdate in 'uVipPassWordUpdate.pas' {VIPPswdupdate},
  uInputVipPswdFrm in 'uInputVipPswdFrm.pas' {InputVipPswdFrm},
  uPlayTypeView in 'OtherBill\uPlayTypeView.pas' {playTypeViewFrm},
  uSelectMaterialInfo in 'OtherBill\uSelectMaterialInfo.pas' {SelectMaterialInfoFrm},
  uAlterLevel in 'BaseData\uAlterLevel.pas' {AlterLevelFrm},
  uTreeBaseEditFrm in 'Base\uTreeBaseEditFrm.pas' {TreeBaseEditFrm},
  uSystemMenuEditFrm in 'BaseData\uSystemMenuEditFrm.pas' {SystemMenuEditFrm},
  uAssDataItemEditFrm in 'BaseData\uAssDataItemEditFrm.pas' {AssDataItemEditFrm},
  uAssDataTypeEditFrm in 'BaseData\uAssDataTypeEditFrm.pas' {AssDataTypeEditFrm},
  uListFormBaseFrm in 'BaseData\uListFormBaseFrm.pas' {ListFormBaseFrm},
  uSelecDataBaseFrm in 'BaseData\uSelecDataBaseFrm.pas' {SelecDataBaseFrm},
  uSelectClientFrm in 'BaseData\uSelectClientFrm.pas' {SelectClientFrm},
  uselectSuppliersFrm in 'BaseData\uselectSuppliersFrm.pas' {selectSuppliersFrm},
  uSelectWarehouseFrm in 'BaseData\uSelectWarehouseFrm.pas' {SelectWarehouseFrm},
  uGroupStandard in 'BaseData\uGroupStandard.pas' {GroupStandardFrm},
  uBranchEditFrm in 'BaseData\uBranchEditFrm.pas' {BranchEditFrm},
  uUserInfofrm in 'BaseData\uUserInfofrm.pas' {FM_UserInfoForm},
  uUserEditfrm in 'BaseData\uUserEditfrm.pas' {FM_UserEditForm},
  uMaterTypeTreeEditFrm in 'BaseData\uMaterTypeTreeEditFrm.pas' {MaterTypeTreeEditFrm},
  uClienSupperTreeEditFrm in 'BaseData\uClienSupperTreeEditFrm.pas' {ClienSupperTreeEditFrm},
  uSelectMaterialFrm in 'BaseData\uSelectMaterialFrm.pas' {SelectMaterialFrm},
  uUserRolefrm in 'BaseData\uUserRolefrm.pas' {FM_UserRoleForm},
  StringUtilClass in '..\Comm\StringUtilClass.pas',
  uMsgListDlg in 'Base\uMsgListDlg.pas' {MsgListDlg},
  uMaterialEditFrm in 'BaseData\uMaterialEditFrm.pas' {uDrpHelperClass},
  uUserBranchScopefrm in 'BaseData\uUserBranchScopefrm.pas' {FM_UserBranchScopeForm},
  uOrgFrm in 'BaseData\uOrgFrm.pas' {OrgFrm},
  uMaterDataSelectHelper in 'HelperClass\uMaterDataSelectHelper.pas',
  uSelectData in 'BaseData\uSelectData.pas',
  uRoleListfrm in 'BaseData\uRoleListfrm.pas' {FM_RoleListForm},
  uRoleEditFrm in 'BaseData\uRoleEditFrm.pas' {FM_RoleEditForm},
  uAllocUserfrm in 'BaseData\uAllocUserfrm.pas' {FM_AllocUserRole},
  uCustomerEditfrm in 'BaseData\uCustomerEditfrm.pas' {FM_CUstomerEditForm},
  uDrpHelperClase in 'HelperClass\uDrpHelperClase.pas',
  uWarehouseEditFrm in 'BaseData\uWarehouseEditFrm.pas' {WarehouseEditFrm},
  uSupplierEditFrm in 'BaseData\uSupplierEditFrm.pas' {STBaseEdit1},
  uWarehouseSetFrm in 'BaseData\uWarehouseSetFrm.pas' {WarehouseSetFrm},
  uDepartmentFrm in 'BaseData\uDepartmentFrm.pas' {DepartmentFrm},
  uPersonListFrm in 'BaseData\uPersonListFrm.pas' {PersonListFrm},
  uuPersonEditFrm in 'BaseData\uuPersonEditFrm.pas' {uPersonEditFrm},
  uParaNavMenuItemfrm in 'BaseData\uParaNavMenuItemfrm.pas' {FM_ParaNavMenuItemForm},
  uParameterSetfrm in 'BaseData\uParameterSetfrm.pas' {FM_ParamSetForm},
  uSelectParamScopefrm in 'BaseData\uSelectParamScopefrm.pas' {FM_SelectParamScopeForm},
  uBaseDataListFrm in 'BaseData\uBaseDataListFrm.pas' {BaseDataListFrm},
  uBasedataEditFrm in 'BaseData\uBasedataEditFrm.pas' {BasedataEditFrm},
  uCodeTableFrm in 'BaseData\uCodeTableFrm.pas' {CodeTableFrm},
  uCodeTableEditFrm in 'BaseData\uCodeTableEditFrm.pas' {CodeTableEditFrm},
  uParamEditfrm in 'BaseData\uParamEditfrm.pas' {FM_ParamEditForm},
  uSizeGroupListFrm in 'BaseData\uSizeGroupListFrm.pas' {SizeGroupListFrm},
  uSizeGroupEditFrm in 'BaseData\uSizeGroupEditFrm.pas' {SizeGroupEditFrm},
  uReadCodeScenarioListFrm in 'BaseData\uReadCodeScenarioListFrm.pas' {ReadCodeScenarioListFrm},
  uReadCodeScenarioEditFrm in 'BaseData\uReadCodeScenarioEditFrm.pas' {ReadCodeScenarioEditFrm},
  uPermissionsEditFrm in 'BaseData\uPermissionsEditFrm.pas' {PermissionsEditFrm},
  PermissionAgtFrm in 'BaseData\PermissionAgtFrm.pas' {PermissionAssignmentFrm},
  uBillQueryFrm in 'BaseData\uBillQueryFrm.pas' {BillQueryFrm},
  uBillQuerySQLEditFrm in 'BaseData\uBillQuerySQLEditFrm.pas' {BillQuerySQLEditFrm},
  uBillListQueryDialogFrm in 'BaseData\uBillListQueryDialogFrm.pas' {BillListQueryDialogFrm},
  uBillQuerySelectFrm in 'BaseData\uBillQuerySelectFrm.pas' {BillQuerySelectFrm},
  uBillQuerySelectDateFrm in 'BaseData\uBillQuerySelectDateFrm.pas' {BillQuerySelectDateFrm},
  uSmsSystemSetFrm in 'BaseData\uSmsSystemSetFrm.pas' {SmsSystemSetFrm},
  uSmsSendQueryFrm in 'BaseData\uSmsSendQueryFrm.pas' {SmsSendQueryFrm},
  uPrintQueryFrm in 'BaseData\uPrintQueryFrm.pas' {PrintQueryFrm},
  uPrintTemplateDesign in 'BaseData\uPrintTemplateDesign.pas' {PrintTemplateDesign},
  uINTERCODEPREFIXEdit in 'BaseData\uINTERCODEPREFIXEdit.pas' {INTERCODEPREFIXEditFrm},
  uINTERCODEPREFIXListFrm in 'BaseData\uINTERCODEPREFIXListFrm.pas' {INTERCODEPREFIXListFrm},
  uCreateInterCode in 'BaseData\uCreateInterCode.pas' {CreateInterCode},
  uBarCodePrintFrm in 'BaseData\uBarCodePrintFrm.pas' {BarCodePrintFrm},
  uI3BaseFrm in 'Base\uI3BaseFrm.pas' {I3BaseFrm},
  uPrintTemplateSelectFrm in 'BaseData\uPrintTemplateSelectFrm.pas' {PrintTemplateSelectFrm},
  uAlterPriceEditFrm in 'BaseData\uAlterPriceEditFrm.pas' {AlterPriceEditFrm},
  uAlterPriceListFrm in 'BaseData\uAlterPriceListFrm.pas' {AlterPriceListFrm},
  uPriceAlterGuide in 'BaseData\uPriceAlterGuide.pas' {PriceAlterGuide},
  uAlterPriceQuery in 'BaseData\uAlterPriceQuery.pas' {AlterPriceQuery},
  uBillEditPurRequset in 'OtherBill\uBillEditPurRequset.pas' {FM_BillEditPurRequest},
  uBillEditPurReceive in 'OtherBill\uBillEditPurReceive.pas' {FM_BillEditPurReceive},
  uBillEditPurInStock in 'OtherBill\uBillEditPurInStock.pas' {FM_BillEditPurInStock},
  uBillEditSaleOrder in 'SaleBIll\uBillEditSaleOrder.pas' {FM_BillEditSaleOrder},
  uBillList_SaleOrder in 'SaleBIll\uBillList_SaleOrder.pas' {FM_BillListSaleOrder},
  uBillEditPostReq in 'SaleBIll\uBillEditPostReq.pas' {FM_BillEditPostReq},
  uBillListPurInStock in 'OtherBill\uBillListPurInStock.pas' {FM_BillListPurInStock},
  uBillListPurReceive in 'OtherBill\uBillListPurReceive.pas' {FM_BillListPurReceive},
  uBillList_PostReq in 'SaleBIll\uBillList_PostReq.pas' {FM_BillListPostReq},
  uShopAlterPriceEditFrm in 'BaseData\uShopAlterPriceEditFrm.pas' {ShopAlterPriceEditFrm},
  uShopAlterPriceListFrm in 'BaseData\uShopAlterPriceListFrm.pas' {ShopAlterPriceListFrm},
  uShopPriceAlterGuide in 'BaseData\uShopPriceAlterGuide.pas' {ShopPriceAlterGuide},
  uPriceQueryFrm in 'BaseData\uPriceQueryFrm.pas' {PriceQueryFrm},
  uBillEditSaleIssue in 'SaleBIll\uBillEditSaleIssue.pas' {FM_BillEditSaleIssue},
  uShopAlterPriceQuery in 'BaseData\uShopAlterPriceQuery.pas' {ShopAlterPriceQuery},
  uBillList_SaleIssue in 'SaleBIll\uBillList_SaleIssue.pas' {FM_BillListSaleIssue},
  uBillEditBranchPO in 'OtherBill\uBillEditBranchPO.pas' {FM_BillEditBranchPO},
  uBillList_BranchPO in 'OtherBill\uBillList_BranchPO.pas' {FM_BillListBranchPO},
  uPubThreadQuery in 'Base\uPubThreadQuery.pas',
  uFindBillQueryFrm in 'BaseData\uFindBillQueryFrm.pas' {FindBillQueryFrm},
  uBillUpDownQueryFrm in 'Base\uBillUpDownQueryFrm.pas' {BillUpDownQueryFrm},
  uBillEditPurReturns in 'OtherBill\uBillEditPurReturns.pas' {FM_BillEditPurRetuens},
  uRemindConfigFrm in 'BaseData\uRemindConfigFrm.pas' {RemindConfigFrm},
  uUserRemindConfigFrm in 'BaseData\uUserRemindConfigFrm.pas' {UserRemindConfigFrm},
  uBillListPurRequest in 'OtherBill\uBillListPurRequest.pas' {FM_BillListPurRequest},
  uBillEditSaleIssueReturn in 'SaleBIll\uBillEditSaleIssueReturn.pas' {FM_BillEditSaleIssueReturn},
  uBillList_SaleIssueReturn in 'SaleBIll\uBillList_SaleIssueReturn.pas' {FM_BillListSaleIssueReturn},
  uTransactionFrm in 'BaseData\uTransactionFrm.pas' {TransactionFrm},
  uTransactionLogQuery in 'BaseData\uTransactionLogQuery.pas' {TransactionLogQuery},
  uBillEditPurReturnWarehs in 'OtherBill\uBillEditPurReturnWarehs.pas' {FM_BillEditPurReturnWarehs},
  uBillEditSaleReturnRequest in 'SaleBIll\uBillEditSaleReturnRequest.pas' {FM_BillEditSaleReturnRequest},
  uBillListSaleReturnRequest in 'SaleBIll\uBillListSaleReturnRequest.pas' {FM_BillListSaleReturnRequest},
  uBillEditChanelTrans in 'SaleBIll\uBillEditChanelTrans.pas' {FM_BillEditChanelTrans},
  uBillListChanelTrans in 'SaleBIll\uBillListChanelTrans.pas' {FM_BillListChanelTrans},
  uExportToAccess in 'Base\uExportToAccess.pas' {ExportMainFrm},
  uPushandpullBillBaseFrm in 'Base\uPushandpullBillBaseFrm.pas' {PushandpullBillBaseFrm},
  uBillDistributionFrm in 'OtherBill\uBillDistributionFrm.pas' {BillDistributionFrm},
  uMaterialDistributionFrm in 'OtherBill\uMaterialDistributionFrm.pas' {MaterialDistributionFrm},
  uStockDistributionFrm in 'OtherBill\uStockDistributionFrm.pas' {StockDistributionFrm},
  uSaleOrderToPostReq in 'CreateBill\uSaleOrderToPostReq.pas' {SaleOrderToPostReqFrm},
  uBillListPurReturnWarehs in 'OtherBill\uBillListPurReturnWarehs.pas' {FM_BillListPurReturWarehs},
  uPackingListFrm in 'OtherBill\uPackingListFrm.pas' {PackingListFrm},
  uBillEditOtherissuebill in 'OtherBill\uBillEditOtherissuebill.pas' {FM_BillEditOtherIssuebill},
  uBillEditOtherinwarehsbill in 'OtherBill\uBillEditOtherinwarehsbill.pas' {FM_BillEditOtherInwarehsbill},
  uBillListOtherIssuebillfrm in 'OtherBill\uBillListOtherIssuebillfrm.pas' {FM_BillListOtherIssuebill},
  uBillListOtherInwarehsbillfrm in 'OtherBill\uBillListOtherInwarehsbillfrm.pas' {FM_BillListOtherInwarehsbill},
  uPackingQueryFrm in 'OtherBill\uPackingQueryFrm.pas' {PackingQueryFrm},
  uPackingListReportFrm in 'OtherBill\uPackingListReportFrm.pas' {PackingReportFrm},
  uBatchCancelPackingFrm in 'OtherBill\uBatchCancelPackingFrm.pas' {BatchCancelPackingFrm},
  uI3AboutFrm in 'OtherBill\uI3AboutFrm.pas' {I3AboutFrm},
  uCreditFileFrm in 'BaseData\uCreditFileFrm.pas' {CreditFileFrm},
  uOtherBillBaseEditFrm in 'Base\uOtherBillBaseEditFrm.pas' {OtherBillBaseEditFrm},
  uBillEditInvInitfrm in 'OtherBill\uBillEditInvInitfrm.pas' {FM_BillEditInvInitForm},
  uBillListInvInitFrm in 'OtherBill\uBillListInvInitFrm.pas' {FM_BillListInvInitForm},
  uFrm_SCMCheckBill in 'OtherBill\uFrm_SCMCheckBill.pas' {Frm_SCMCheckBill},
  uBillListSCMCheck in 'OtherBill\uBillListSCMCheck.pas' {FM_BillListSCMCheck},
  uSCMCheckSaveStorageFrm in 'OtherBill\uSCMCheckSaveStorageFrm.pas' {Frm_SCMCheckSaveStorage},
  uBillPromotion in 'SaleBIll\uBillPromotion.pas' {FM_BillPromotionEdit},
  uTicketRequisition in 'POSEdit\uTicketRequisition.pas' {TicketRequisitionFrm},
  uTicketRequisitionList in 'POSEdit\uTicketRequisitionList.pas' {TicketRequisitionList},
  uMallCompareListFrm in 'POSEdit\uMallCompareListFrm.pas' {MallCompareListFrm},
  uMallCompareEditFrm in 'POSEdit\uMallCompareEditFrm.pas' {MallCompareEditFrm},
  uMallCompareFrm in 'POSEdit\uMallCompareFrm.pas' {MallCompareFrm},
  uBatchAlterOrderColorFrm in 'SaleBIll\uBatchAlterOrderColorFrm.pas' {BatchAlterOrderColorFrm},
  uBatchCloseOrderFrm in 'SaleBIll\uBatchCloseOrderFrm.pas' {BatchCloseOrderFrm},
  uOrderAllocateFrm in 'SaleBIll\uOrderAllocateFrm.pas' {OrderAllocateFrm},
  uBatchCancelAllocationFrm in 'SaleBIll\uBatchCancelAllocationFrm.pas' {BatchCancelAllocationFrm},
  uBillListPromtion in 'SaleBIll\uBillListPromtion.pas' {FM_BillListPromt},
  uSaleOrderQueryFrm in 'SaleBIll\uSaleOrderQueryFrm.pas' {SaleOrderQueryFrm},
  uServiceAttributeFrm in 'BaseData\uServiceAttributeFrm.pas' {ServiceAttributeFrm},
  uServiceAttributeAllocationFrm in 'BaseData\uServiceAttributeAllocationFrm.pas' {ServiceAttributeAllocationFrm},
  uPostReqToIsSueFrm in 'CreateBill\uPostReqToIsSueFrm.pas' {PostReqToIsSueFrm},
  uPostReqQueryFrm in 'SaleBIll\uPostReqQueryFrm.pas' {PostReqQueryFrm},
  uPurOrderSumImpfrm in 'OtherBill\uPurOrderSumImpfrm.pas' {PurOrderSumImpForm},
  uRepairEditFrm in 'OtherBill\uRepairEditFrm.pas' {RepairEditFrm},
  uRepairListFrm in 'OtherBill\uRepairListFrm.pas' {RepairListFrm},
  uSaleFormTxtImport in 'SaleBIll\uSALEFormTxtImport.pas' {SaleFormTxtImportFrm},
  uBatchAddOrderMaterialFrm in 'SaleBIll\uBatchAddOrderMaterialFrm.pas' {BatchAddOrderMaterialFrm},
  uMoveIssueToMoveInFrm in 'CreateBill\uMoveIssueToMoveInFrm.pas' {MoveIssueToMoveInFrm},
  uMoveIssueBillQuery in 'OtherBill\uMoveIssueBillQuery.pas' {MoveIssueBillQuery},
  uBillEditStocktransferfrm in 'OtherBill\uBillEditStocktransferfrm.pas' {FM_BillEditStockTransFerForm};

{$R *.res}
{$I- } //不产生I/O异常类而是把错误代码返回到预定义变量IOResult中
begin
  if Pos('-',DateToStr(date))<=0 then
  begin
    ShowMsg(application.Handle, '系统日期格式必须更改为长日期格式(yyyy-MM-dd),例:1999-09-01',[]);
  end
  else
  begin
    Application.Initialize;
    Application.Title := 'I3鞋服ERP系统';
    Application.CreateForm(TCliDM, CliDM);
  Application.CreateForm(TFMCliMain, FMCliMain);
  Application.Run;
  end;
end.
